/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package straightway.peerspace.net.impl

import com.nhaarman.mockito_kotlin.mock
import com.nhaarman.mockito_kotlin.verify
import org.junit.jupiter.api.Test
import straightway.peerspace.net.Configuration
import straightway.peerspace.net.InfrastructureReceiver
import straightway.testing.bdd.Given
import straightway.testing.testAutoGeneratedDataClassMethods
import kotlin.reflect.KClass
import kotlin.reflect.full.memberProperties

class InfrastructureImplTest {

    @Test
    fun `auto-generated data class methods`() =
            createInfrastructure().testAutoGeneratedDataClassMethods()

    @Test
    fun `infrastructure is set to dataQueryHandler`() =
            Given { createInfrastructure(dataQueryHandler = mock()) } when_ {
                dataQueryHandler
            } then {
                verify(it.result).infrastructure = this
            }

    @Test
    fun `infrastructure is set to members implementing InfrastructureReceiver`() {
        val infrastructureReceiverClass = arrayOf<KClass<out Any>>(InfrastructureReceiver::class)
        val sut = InfrastructureImpl(
                dataChunkStore = mock(infrastructureReceiverClass),
                peerDirectory = mock(infrastructureReceiverClass),
                network = mock(infrastructureReceiverClass),
                configuration = Configuration(),
                knownPeerQueryChooser = mock(infrastructureReceiverClass),
                knownPeerAnswerChooser = mock(infrastructureReceiverClass),
                forwardStrategy = mock(infrastructureReceiverClass),
                timeProvider = mock(infrastructureReceiverClass),
                dataQueryHandler = mock(infrastructureReceiverClass),
                dataPushForwarder = mock(infrastructureReceiverClass),
                knownPeersProvider = mock(infrastructureReceiverClass))
        InfrastructureImpl::class.memberProperties.forEach {
            val currProperty = it.get(sut)
            if (currProperty is InfrastructureReceiver)
                verify(currProperty).infrastructure = sut
        }
    }
}