/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package straightway.peerspace.net

import com.nhaarman.mockito_kotlin.mock
import org.junit.jupiter.api.Test
import straightway.peerspace.data.DataQuery
import straightway.peerspace.data.Id
import straightway.peerspace.data.Identifyable
import straightway.peerspace.data.untimedData
import straightway.utils.deserializeTo
import straightway.utils.serializeToByteArray
import straightway.testing.bdd.Given
import straightway.testing.flow.Equal
import straightway.testing.flow.Null
import straightway.testing.flow.expect
import straightway.testing.flow.is_
import straightway.testing.flow.to_
import straightway.testing.testAutoGeneratedDataClassMethods

class DataQueryRequestTest {

    private companion object {
        val originatorId = Id("originatorId")
        val matchedId = Id("matchedId")
        val matchedIdentifyable = mock<Identifyable> {
            on { id }.thenReturn(matchedId)
        }
    }

    @Test
    fun testAutoGeneratedDataClassMethods() {
        val sut = DataQueryRequest(originatorId, DataQuery(matchedId, 1L..1L, epoch = 1))
        sut.testAutoGeneratedDataClassMethods()
    }

    @Test
    fun `construction with Id instance creates query with given originator id`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedId)) } when_ {
                originatorId
            } then {
                expect(it.result is_ Equal to_ DataQueryRequestTest.originatorId)
            }

    @Test
    fun `construction with Id instance creates query for id`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedId)) } when_ {
                id
            } then {
                expect(it.result is_ Equal to_ matchedId)
            }

    @Test
    fun `construction with Id instance creates query with zero timestamp range`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedId)) } when_ {
                timestamps
            } then {
                expect(it.result is_ Equal to_ LongRange(0L, 0L))
            }

    @Test
    fun `construction with Identifyable creates query with given originator id`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedIdentifyable)) } when_ {
                originatorId
            } then {
                expect(it.result is_ Equal to_ DataQueryRequestTest.originatorId)
            }

    @Test
    fun `construction with Identifyable creates query for id`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedIdentifyable)) } when_ {
                id
            } then {
                expect(it.result is_ Equal to_ matchedId)
            }

    @Test
    fun `construction with Identifyable creates query with zero timestamp range`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedIdentifyable)) } when_ {
                timestamps
            } then {
                expect(it.result is_ Equal to_ LongRange(0L, 0L))
            }

    @Test
    fun `construction with epoch and null timestamp range set null epoch`() =
            Given {
                DataQueryRequest(originatorId, DataQuery(matchedId, 0L..0L, 83))
            } when_ {
                epoch
            } then {
                expect(it.nullableResult is_ Null)
            }

    @Test
    fun `has serialVersionUID`() =
            expect(DataQueryRequest.serialVersionUID is_ Equal to_ 1L)

    @Test
    fun `is serializable`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedId, 1L..2L)) } when_ {
                val serialized = serializeToByteArray()
                serialized.deserializeTo<DataQueryRequest>()
            } then {
                expect(it.result is_ Equal to_ this)
            }

    @Test
    fun `contains originator id`() =
            Given { DataQueryRequest(originatorId, DataQuery(matchedId, untimedData)) } when_ {
                this.originatorId
            } then {
                expect(it.result is_ Equal to_ originatorId)
            }

    @Test
    fun `identification is same as the query without originator id`() =
            Given {
                DataQueryRequest(originatorId, DataQuery(matchedId, 1L..1L))
            } when_ {
                identification
            } then {
                expect(it.result is_ Equal to_ DataQuery(matchedId, 1L..1L))
            }

    @Test
    fun `withOriginator returns object equal in all aspects expect originator id`() =
            Given {
                DataQueryRequest(originatorId, DataQuery(matchedId, 1L..1L))
            } when_ {
                withOriginator(Id("newOriginator"))
            } then {
                expect(it.result is_ Equal to_ this.copy(originatorId = Id("newOriginator")))
            }

    @Test
    fun `toString for untimed query`() =
            expect(DataQueryRequest(Id("originator"), DataQuery(Id("chunk"))).toString()
                           is_ Equal to_ "Request originator: DataQuery(chunk)")

    @Test
    fun `toString for timed query`() =
            expect(DataQueryRequest(Id("originator"), DataQuery(Id("chunk"), 1L..2L)).toString()
                           is_ Equal to_ "Request originator: DataQuery(chunk[1..2])")

    @Test
    fun `toString for timed query with epoch`() =
            expect(DataQueryRequest(
                    Id("originator"),
                    DataQuery(Id("chunk"), 1L..2L, 83)).toString()
                   is_ Equal to_ "Request originator: DataQuery(chunk[1..2|83])")
}
