/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package straightway.peerspace.net

import org.junit.jupiter.api.Test
import straightway.testing.flow.Empty
import straightway.testing.flow.expect
import straightway.testing.flow.is_
import straightway.testing.testAutoGeneratedDataClassMethods

class ForwardStateTest {

    @Test
    fun `auto-generated data class methods`() =
            ForwardState().testAutoGeneratedDataClassMethods()

    @Test
    fun `successful is initially empty`() =
            expect(ForwardState().successful is_ Empty)

    @Test
    fun `failed is initially empty`() =
            expect(ForwardState().failed is_ Empty)

    @Test
    fun `pending is initially empty`() =
            expect(ForwardState().pending is_ Empty)
}