/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package straightway.peerspace.transport

import com.nhaarman.mockito_kotlin.mock
import org.junit.jupiter.api.Test
import straightway.peerspace.crypto.Encryptor
import straightway.peerspace.crypto.Signer
import straightway.testing.bdd.Given
import straightway.testing.flow.Same
import straightway.testing.flow.as_
import straightway.testing.flow.expect
import straightway.testing.flow.is_
import straightway.testing.testAutoGeneratedDataClassMethods

class ChunkerCryptoTest {

    @Test
    fun testAutoGeneratedDataClassMethods() =
            ChunkerCrypto(mock(), mock()).testAutoGeneratedDataClassMethods()

    @Test
    fun `signatureChecker is accessible`() {
        val signerIn: Signer = mock()
        Given {
            ChunkerCrypto(signer = signerIn)
        } when_ {
            signer
        } then {
            expect(it.result is_ Same as_ signerIn)
        }
    }

    @Test
    fun `decryptor is accessible`() {
        val encryptorIn: Encryptor = mock()
        Given {
            ChunkerCrypto(encryptor = encryptorIn)
        } when_ {
            encryptor
        } then {
            expect(it.result is_ Same as_ encryptorIn)
        }
    }
}