/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package straightway.peerspace.data

import org.junit.jupiter.api.Test
import straightway.testing.flow.Equal
import straightway.testing.flow.expect
import straightway.testing.flow.is_
import straightway.testing.flow.to_
import straightway.testing.testAutoGeneratedDataClassMethods
import straightway.utils.serializeToByteArray
import straightway.utils.deserializeTo

class ChunkTest {

    private companion object {
        val chunkId = Id("1234")
        val chunkData = "data"
    }

    @Test
    fun `key is as specified in construction`() =
            expect(Chunk(Key(chunkId), chunkData).key is_ Equal to_ Key(chunkId))

    @Test
    fun `data is as specified in construction`() =
            expect(Chunk(Key(chunkId), chunkData).data is_ Equal to_ chunkData)

    @Test
    fun `Chunk is serializable`() {
        val sut = Chunk(Key(chunkId), chunkData)
        val serialized = sut.serializeToByteArray()
        val deserialized = serialized.deserializeTo<Chunk>()
        expect(deserialized is_ Equal to_ sut)
    }

    @Test
    fun `has serialVersionUID`() =
            expect(Chunk.serialVersionUID is_ Equal to_ 1L)

    @Test
    fun `auto-generated data class members`() =
            Chunk(Key(chunkId), chunkData).testAutoGeneratedDataClassMethods()
}