/*
 * Copyright 2016 github.com/straightway
 *
 *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package straightway.peerspace.data

import org.junit.jupiter.api.Test
import straightway.utils.deserializeTo
import straightway.utils.serializeToByteArray
import straightway.testing.bdd.Given
import straightway.testing.flow.Equal
import straightway.testing.flow.False
import straightway.testing.flow.Null
import straightway.testing.flow.True
import straightway.testing.flow.expect
import straightway.testing.flow.is_
import straightway.testing.flow.to_
import straightway.testing.testAutoGeneratedDataClassMethods

class DataChunkQueryTest {

    private companion object {
        val matchedId = Id("matchedId")
        val unmatchedId = Id("unmatchedId")
    }

    @Test
    fun testAutoGeneratedDataClassMethods() {
        val sut = DataChunkQuery(matchedId, 1L..1L, epoch = 1)
        sut.testAutoGeneratedDataClassMethods()
    }

    @Test
    fun `construction with Id instance creates query for chunk id`() =
            Given { DataChunkQuery(matchedId) } when_ {
                chunkId
            } then {
                expect(it.result is_ Equal to_ matchedId)
            }

    @Test
    fun `construction with Id instance creates query with zero timestamp range`() =
            Given { DataChunkQuery(matchedId) } when_ {
                timestamps
            } then {
                expect(it.result is_ Equal to_ LongRange(0L, 0L))
            }

    @Test
    fun `construction with epoch and null timestamp range set null epoch`() =
            Given {
                DataChunkQuery(matchedId, 0L..0L, 83)
            } when_ {
                epoch
            } then {
                expect(it.nullableResult is_ Null)
            }

    @Test
    fun `matches key with given id and zero timestamp`() =
            Given { DataChunkQuery(matchedId, untimedData) } when_ {
                isMatching(Key(matchedId))
            } then {
                expect(it.result is_ True)
            }

    @Test
    fun `does not match key with given id and non-zero timestamp`() =
            Given { DataChunkQuery(matchedId, untimedData) } when_ {
                isMatching(Key(matchedId, 1, 0))
            } then {
                expect(it.result is_ False)
            }

    @Test
    fun `does not match key with other id`() =
            Given { DataChunkQuery(matchedId, untimedData) } when_ {
                isMatching(Key(unmatchedId))
            } then {
                expect(it.result is_ False)
            }

    @Test
    fun `matches timestamp within range`() =
            Given { DataChunkQuery(matchedId, 1L..2L) } when_ {
                isMatching(Key(matchedId, 1, 0)) && isMatching(Key(matchedId, 2, 0))
            } then {
                expect(it.result is_ True)
            }

    @Test
    fun `matches not timestamp outside range`() =
            Given { DataChunkQuery(matchedId, 1L..2L) } when_ {
                isMatching(Key(matchedId)) || isMatching(Key(matchedId, 3, 0))
            } then {
                expect(it.result is_ False)
            }

    @Test
    fun `id is same as chunkId`() =
            Given { DataChunkQuery(matchedId) } when_ {
                id
            } then {
                expect(it.result is_ Equal to_ matchedId)
            }

    @Test
    fun `has serialVersionUID`() =
            expect(DataChunkQuery.serialVersionUID is_ Equal to_ 1L)

    @Test
    fun `is serializable`() =
            Given { DataChunkQuery(matchedId, 1L..2L) } when_ {
                val serialized = serializeToByteArray()
                serialized.deserializeTo<DataChunkQuery>()
            } then {
                expect(it.result is_ Equal to_ this)
            }

    @Test
    fun `isUntimed if the timestamp range is 0L to 0L`() =
            Given { DataChunkQuery(matchedId, untimedData) } when_ {
                isUntimed
            } then {
                expect(it.result is_ True)
            }

    @Test
    fun `isUntimed if the timestamp range is other than 0L to 0L`() =
            Given { DataChunkQuery(matchedId, 1L..1L) } when_ {
                isUntimed
            } then {
                expect(it.result is_ False)
            }

    @Test
    fun `withEpoch returns queryRequest with given epoch set`() =
            Given { DataChunkQuery(matchedId, 1L..1L) } when_ {
                withEpoch(1)
            } then {
                expect(it.result.epoch is_ Equal to_ 1)
            }

    @Test
    fun `withEpoch returns queryRequest with same matching chunk id`() =
            Given { DataChunkQuery(matchedId, 1L..1L) } when_ {
                withEpoch(1)
            } then {
                expect(it.result.chunkId is_ Equal to_ matchedId)
            }

    @Test
    fun `withEpoch returns queryRequest with same timestamps range`() =
            Given { DataChunkQuery(matchedId, 1L..1L) } when_ {
                withEpoch(1)
            } then {
                expect(it.result.timestamps is_ Equal to_ 1L..1L)
            }

    @Test
    fun `withEpoch returns same queryRequest for untimed query requests`() =
            Given { DataChunkQuery(matchedId) } when_ {
                withEpoch(1)
            } then {
                expect(it.result is_ Equal to_ DataChunkQuery(matchedId))
            }

    @Test
    fun `toString for untimed query`() =
            expect(DataChunkQuery(Id("chunk")).toString()
                           is_ Equal to_ "DataChunkQuery(chunk)")

    @Test
    fun `toString for timed query`() =
            expect(DataChunkQuery(Id("chunk"), 1L..2L).toString()
                           is_ Equal to_ "DataChunkQuery(chunk[1..2])")

    @Test
    fun `toString for timed query with epoch`() =
            expect(DataChunkQuery(Id("chunk"), 1L..2L, 83).toString()
                           is_ Equal to_ "DataChunkQuery(chunk[1..2|83])")
}
